# Generated by Django 4.1.1 on 2022-10-01 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estilo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoRepresentado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_trabajo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_obra', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('anno', models.CharField(max_length=25)),
                ('ubicacion', models.CharField(max_length=100)),
                ('iconografia', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('nombre_archivo', models.CharField(max_length=100)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trama.estilo')),
                ('tipo_de_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trama.tipodeobra')),
                ('trabajo_representado', models.ManyToManyField(to='trama.trabajorepresentado')),
            ],
        ),
    ]
