# Generated by Django 4.1.1 on 2022-10-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trama', '0002_remove_obra_nombre_archivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='url_externa',
            field=models.CharField(help_text='URL con contexto', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='url_imagen',
            field=models.CharField(help_text='URL externa del archivo de imagen (si la hay)', max_length=512, null=True),
        ),
    ]
