# Generated by Django 4.1.2 on 2022-10-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trama', '0003_obra_url_externa_obra_url_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='anno',
            field=models.CharField(help_text='Año (exacto o aproximado) de creación de la obra', max_length=64, verbose_name='Año o época aproximada de la obra'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='descripcion',
            field=models.TextField(help_text='Descripción de la obra en texto libre', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='iconografia',
            field=models.CharField(help_text='Breve descripción de la iconografía representada', max_length=128, verbose_name='Iconografía'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='ubicacion',
            field=models.CharField(help_text='Ubicación de la obra (museo, colección particular...)', max_length=128, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='url_externa',
            field=models.CharField(blank=True, help_text='URL con contexto', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='url_imagen',
            field=models.CharField(blank=True, help_text='URL externa del archivo de imagen (si la hay)', max_length=512, null=True),
        ),
    ]
