# Generated by Django 4.1.1 on 2023-01-06 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trama', '0004_alter_obra_anno_alter_obra_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Autor de la obra', max_length=256)),
                ('alias', models.CharField(help_text='Alias u otros nombres por los que el artista es conocido', max_length=256, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='obra',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trama.autor'),
        ),
    ]
